//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessHole
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutCome
    {
        public int Id { get; set; }
        public string WhatFor { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
